[[redirects]]
  from = "/api/football/*"
  to = "https://v3.football.api-sports.io"
  status = 200
  force = true
  [redirects.headers]
		x-rapidapi-key: import.meta.env.VITE_FOOTBALL_API_KEY
		x-rapidapi-host: "v3.football.api-sports.io"