/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FootballFixturesIdImport } from './routes/football/fixtures/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const FootballFixturesIndexLazyImport = createFileRoute('/football/fixtures/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const FootballFixturesIndexLazyRoute = FootballFixturesIndexLazyImport.update({
  id: '/football/fixtures/',
  path: '/football/fixtures/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/football/fixtures/index.lazy').then((d) => d.Route),
)

const FootballFixturesIdRoute = FootballFixturesIdImport.update({
  id: '/football/fixtures/$id',
  path: '/football/fixtures/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/football/fixtures/$id': {
      id: '/football/fixtures/$id'
      path: '/football/fixtures/$id'
      fullPath: '/football/fixtures/$id'
      preLoaderRoute: typeof FootballFixturesIdImport
      parentRoute: typeof rootRoute
    }
    '/football/fixtures/': {
      id: '/football/fixtures/'
      path: '/football/fixtures'
      fullPath: '/football/fixtures'
      preLoaderRoute: typeof FootballFixturesIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/football/fixtures/$id': typeof FootballFixturesIdRoute
  '/football/fixtures': typeof FootballFixturesIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/football/fixtures/$id': typeof FootballFixturesIdRoute
  '/football/fixtures': typeof FootballFixturesIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/football/fixtures/$id': typeof FootballFixturesIdRoute
  '/football/fixtures/': typeof FootballFixturesIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/football/fixtures/$id' | '/football/fixtures'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/football/fixtures/$id' | '/football/fixtures'
  id: '__root__' | '/' | '/football/fixtures/$id' | '/football/fixtures/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FootballFixturesIdRoute: typeof FootballFixturesIdRoute
  FootballFixturesIndexLazyRoute: typeof FootballFixturesIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FootballFixturesIdRoute: FootballFixturesIdRoute,
  FootballFixturesIndexLazyRoute: FootballFixturesIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/football/fixtures/$id",
        "/football/fixtures/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/football/fixtures/$id": {
      "filePath": "football/fixtures/$id.tsx"
    },
    "/football/fixtures/": {
      "filePath": "football/fixtures/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
